
					-- ## -- ## -- ## -- ## -- ## -- ## -- ## -- ## --
					--			MODELO SOLO FIJA  A MT				--
					-- ## -- ## -- ## -- ## -- ## -- ## -- ## -- ## --


-- [ Tabla Exportada de Teradata ] --
-- teradata. (M-1)
SELECT * FROM DBI_PUBLIC.LVV_REPLICA_MRMT_SOLOFIJA WHERE PERIODO='2020-07-01'; 

--# Tabla exportada a sql
SELECT * FROM ARS_REP_SOLOFIJA_MT


-- ADD DECIL.
ALTER TABLE ARS_REP_SOLOFIJA_MT ADD  DECIL INT;

-- [ Actualizamos los Deciles en SQL]
UPDATE ARS_REP_SOLOFIJA_MT
SET DECIL = CASE
WHEN PROB <= 0.3665960 THEN 1
WHEN PROB <= 0.3750556 THEN 2
WHEN PROB <= 0.3868832 THEN 3
WHEN PROB <= 0.4012544 THEN 4
WHEN PROB <= 0.4335337 THEN 5
WHEN PROB <= 0.4534445 THEN 6
WHEN PROB <= 0.4669543 THEN 7
WHEN PROB <= 0.5003771 THEN 8
WHEN PROB <= 0.5184623 THEN 9
WHEN PROB >  0.5184623 THEN 10
END;

-- (06) 1,440,605
-- (0723) 1,450,170
-- (0822) 1482782

SELECT * FROM ARS_REP_SOLOFIJA_MT

-- # Tabla extraida de Teradata :Planta Comercial Atis 
-- # Antiguedad.
SELECT * FROM ARS_Antiguedad_PlantaComerAtis 


-- Actualizamos los valores de antiguedad
ALTER TABLE ARS_REP_SOLOFIJA_MT ADD ANTIGUEDAD_ABONADO_FIJA INT
GO
UPDATE ARS_REP_SOLOFIJA_MT
SET 
	ANTIGUEDAD_ABONADO_FIJA = B.MAX_ANTIGUEDAD_FIJA
FROM 
	ARS_REP_SOLOFIJA_MT A
	INNER JOIN ARS_Antiguedad_PlantaComerAtis B
		ON A.TIPODOC_FIJA = B.TIPO_DOC
		AND A.DOC_FIJA = B.NUM_DOC;

-- 1398927
-- (0722) 1,408,837

SELECT * FROM ARS_REP_SOLOFIJA_MT


					-- ## -- ## -- ## -- ## -- ## -- ## -- ## -- ## --
					--			BASE DE MALOS PAGADORES 			--
					-- ## -- ## -- ## -- ## -- ## -- ## -- ## -- ## --


DROP TABLE REPLICA_SFMT;
SELECT 
	CONVERT(DATE,PERIODO,103) AS PERIODO,
	TIPODOC_FIJA,DOC_FIJA,DECIL,ANTIGUEDAD_ABONADO_FIJA
INTO REPLICA_SFMT
FROM ARS_REP_SOLOFIJA_MT WHERE  FLAG_ANTIG_3M = 1;

--(0722) 1,410,117
-- (0822) 1422090


-- # T2
DROP TABLE REPLICA_SFMT3;
SELECT
	 A.*,
	 CASE WHEN ANTIGUEDAD_ABONADO_FIJA <= 18 THEN 0 ELSE 1 END AS FLAG_18M--,	>18 meses
INTO REPLICA_SFMT3 
FROM  REPLICA_SFMT A;

-- (0722) 1,410,117
-- (0822) 1,422,090

-- # Flag de planta activa : ATIS Y CMS diarias.
SELECT * FROM ARS_PlantaAtis_Diaria
SELECT * FROM ARS_PlantaCms_Diaria


-- ADD 
ALTER TABLE REPLICA_SFMT3 ADD 
	PLANTA_ATIS INT, 
	PLANTA_CMS INT,
	PLANTA_FIJA INT
go
-- Planta Atis Diario
UPDATE REPLICA_SFMT3
SET	PLANTA_ATIS = 1
FROM REPLICA_SFMT3 A
	INNER JOIN (SELECT DISTINCT NUMERODOCUMENTOCLIENTE FROM ARS_PlantaAtis_Diaria) B
	ON A.DOC_FIJA = B.NumeroDocumentoCliente;

-- Planta CMS Diario.
UPDATE REPLICA_SFMT3
SET PLANTA_CMS = 1
FROM REPLICA_SFMT3 A
	INNER JOIN (SELECT DISTINCT NUMERODOCUMENTO FROM ARS_PlantaCms_Diaria) B
	ON A.DOC_FIJA = B.NumeroDocumento;

UPDATE REPLICA_SFMT3
SET PLANTA_FIJA = 1
WHERE PLANTA_ATIS = 1 OR PLANTA_CMS = 1;



-----------------------------
-- Base Malos Pagadores
-----------------------------

-- # M
DROP TABLE BD_MALOS_PAGADORES_M;
SELECT 
	*
INTO
	BD_MALOS_PAGADORES_M
FROM 
	REPLICA_SFMT3
WHERE
	DECIL IN (9,10) AND
	FLAG_18M = 0 AND
	PLANTA_FIJA = 1;


-- (06) --> 204,865
-- (07) --> 146,483
-- (08) 137371


---- # Cluster Plnata : sql # -----
SELECT * FROM ARS_BaseTipo_Cluster 

ALTER TABLE BD_MALOS_PAGADORES_M ADD CLUSTER_PLANTA VARCHAR(50);
GO
UPDATE BD_MALOS_PAGADORES_M
SET
	CLUSTER_PLANTA = B.CLUSTER_PLANTA
FROM
	BD_MALOS_PAGADORES_M A
	INNER JOIN ARS_BaseTipo_Cluster B
		ON A.DOC_FIJA = B.DOCUMENTO;

SELECT * FROM BD_MALOS_PAGADORES_M

-- # Base a Exportar a Teradata : Solo al cluster_planta (SOLOFIJA). # --

-- PERIODO (M-1)
DROP TABLE BASE_MALOS_PAGADORES_FI_20200822;
SELECT 
DISTINCT TIPODOC_FIJA,DOC_FIJA 
INTO BASE_MALOS_PAGADORES_FI_20200822
FROM BD_MALOS_PAGADORES_M
WHERE CLUSTER_PLANTA = '(SoloFija)';


SELECT * FROM BASE_MALOS_PAGADORES_FI_20200822





